<?php

use SohelRana820\Forecast\Forecast;

require __DIR__.'/../config.php';

class ForecastTests extends PHPUnit_Framework_TestCase
{
    /**
     * @var Forecast
     */
    protected $forecast;

    /**
     * @var Forecast;
     */
    protected $response;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->forecast = new Forecast(API_KEY);
        $this->forecast->setLatitude(DEFAULT_LATITUDE);
        $this->forecast->setLongitude(DEFAULT_LATITUDE);
        $this->response = $this->forecast->request();
    }

    public function testValidRequest()
    {
        $forecast = new Forecast('invalid api key');
        $forecast->setLatitude('');
        $forecast->setLongitude('');
        $this->assertNull($forecast->request());
    }

    public function testSecretKeySetterGetter()
    {
        $forecast = new Forecast();
        $forecast->setSecretKey('1111');
        $this->assertEquals('1111', $forecast->getSecretKey());
    }

    public function testTimezoneGetter()
    {
        $this->assertNotNull($this->response->getTimezone());
    }

    public function testRequestResponseIsObject()
    {
        $this->assertTrue(is_object($this->response));
    }

    public function testWeatherCurrentlyData()
    {
        $this->assertTrue(is_array($this->response->getCurrentlyData()));
    }

    public function testWeatherHourlyData()
    {
        $this->assertTrue(is_array($this->response->getHourlyData()));
    }

    public function testWeatherDailyData()
    {
        $this->assertTrue(is_array($this->response->getDailyData()));
    }

    public function testFlags()
    {
        $this->assertTrue(is_array($this->response->getFlags()));
    }
}