<?php

use SohelRana820\Forecast\Forecast;

require __DIR__.'/../config.php';

class ForecastTests extends PHPUnit_Framework_TestCase
{
    /**
     * @var Forecast
     */
    protected $forecast;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->forecast = new Forecast(API_KEY);
        $this->forecast->setLatitude(DEFAULT_LATITUDE);
        $this->forecast->setLongitude(DEFAULT_LATITUDE);
    }

    public function testRequest()
    {
        $options = [];
        $this->forecast->setOptions($options);
        $data = $this->forecast->request();
        $this->assertTrue(is_object($data));
    }
}